data class Post(
    var id : Int = 0,
    val ownerId : Long,
    val fromId : Long,
    val createdBy : Long,
    val date : Long,
    val text : String,
    val replyOwnerId : Long,
    val replyPostId : Long,
    val friendsOnly : Boolean,
    val comments : Comments,
    val copyright : Copyright,
    val likes : Likes,
    val reposts : Reposts,
    val views : Views,
    val postType : String,
    val postSource : PostSource?, // источник записи
    val attachments : Array<Attachment>? = emptyArray(),
    val geo : Geo?, // информация о местоположении
    val signerId : Long,
    val copyHistory : Array<Post>? = emptyArray(),
    val canPin : Boolean,
    val canDelete : Boolean,
    val canEdit : Boolean,
    val isPinned : Boolean,
    val markedAsAds : Boolean,
    val isFavorite : Boolean,
    val donut : Donut,
    val postponedId : Long
)